# Generated by Django 4.1.13 on 2024-12-06 07:11

from django.db import migrations, models
import utils.validators.validators


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='driver_id',
            field=models.CharField(default='059-34-059', max_length=11, unique=True, validators=[utils.validators.validators.DataValidators.validate_ssn]),
        ),
    ]
