# Generated by Django 4.1.13 on 2024-12-08 06:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("driver", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Review",
        ),
    ]
