# Generated by Django 5.1.3 on 2024-11-21 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0002_alter_driver_options_alter_driver_managers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='document_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='driver',
            name='driver_license_image',
            field=models.ImageField(null=True, upload_to='driver_documents/'),
        ),
        migrations.AddField(
            model_name='driver',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='driver_photos/'),
        ),
    ]
