# Generated by Django 5.1.3 on 2024-11-27 18:28

import utils.validators.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("driver", "0004_remove_driver_document_verified_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="driver",
            options={},
        ),
        migrations.AlterField(
            model_name="driver",
            name="phone_number",
            field=models.CharField(
                max_length=11,
                unique=True,
                validators=[utils.validators.validators.DataValidators.validate_ssn],
            ),
        ),
        migrations.AlterField(
            model_name="driver",
            name="state",
            field=models.CharField(
                max_length=2,
                validators=[utils.validators.validators.DataValidators.validate_state],
            ),
        ),
        migrations.AlterField(
            model_name="driver",
            name="zipcode",
            field=models.CharField(
                max_length=10,
                validators=[
                    utils.validators.validators.DataValidators.validate_zipcode
                ],
            ),
        ),
        migrations.AddConstraint(
            model_name="driver",
            constraint=models.UniqueConstraint(
                fields=("email",), name="unique_driver_email"
            ),
        ),
        migrations.AddConstraint(
            model_name="driver",
            constraint=models.UniqueConstraint(
                fields=("phone_number",), name="unique_driver_phone"
            ),
        ),
    ]
