# Generated by Django 5.1.3 on 2024-11-27 19:13

import utils.validators.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("driver", "0005_alter_driver_options_alter_driver_phone_number_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="driver",
            name="phone_number",
            field=models.CharField(
                max_length=16,
                unique=True,
                validators=[utils.validators.validators.DataValidators.validate_ssn],
            ),
        ),
    ]
