version: '3.8'

services:
  web:
    build:
      context: .
    container_name: django_web
    restart: always
    command: >
      sh -c "python manage.py migrate &&
             python manage.py collectstatic --noinput &&
             python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
      - static_data:/app/static
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DJANGO_SETTINGS_MODULE: uber_simulation.settings
      DATABASE_HOST: db
      DATABASE_PORT: 3306
      DATABASE_NAME: uber_simulation_db
      DATABASE_USER: user
      DATABASE_PASSWORD: password

  db:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: uber_simulation_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"

volumes:
  mysql_data:
  static_data: