# Generated by Django 4.1.13 on 2024-12-09 05:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="profile_photo",
            field=models.ImageField(
                blank=True, null=True, upload_to="customer_photos/"
            ),
        ),
    ]
