# Generated by Django 5.1.3 on 2024-12-01 00:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="last_login",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="last login"
            ),
        ),
        migrations.AlterField(
            model_name="customer",
            name="customer_id",
            field=models.CharField(
                max_length=11, primary_key=True, serialize=False, unique=True
            ),
        ),
        migrations.AlterModelTable(
            name="customer",
            table=None,
        ),
    ]
