# Generated by Django 4.1.13 on 2024-12-08 06:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_review"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="is_reviewed",
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name="review",
            name="booking",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reviews",
                to="users.booking",
            ),
        ),
    ]
