# Generated by Django 5.1.3 on 2024-12-01 04:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_customer_last_login_alter_customer_customer_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="status",
            field=models.CharField(
                choices=[
                    ("Pending", "Pending"),
                    ("Accepted", "Accepted"),
                    ("Rejected", "Rejected"),
                    ("Completed", "Completed"),
                ],
                default="Pending",
                max_length=20,
            ),
        ),
    ]
