# Generated by Django 4.1.13 on 2024-12-07 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_booking_available_drivers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='available_drivers',
        ),
        migrations.AddField(
            model_name='booking',
            name='picked_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('accepted', 'accepted'), ('rejected', 'rejected'), ('picked', 'picked'), ('completed', 'completed')], default='Pending', max_length=20),
        ),
    ]
