# Generated by Django 4.1.13 on 2024-12-07 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_booking_available_drivers_booking_picked_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='drop_date',
            field=models.DateTimeField(null=True),
        ),
    ]
