# Generated by Django 5.1.3 on 2024-12-01 04:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0004_booking_driver"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
