apiVersion: apps/v1
kind: Deployment
metadata:
  name: uber-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: uber-frontend
  template:
    metadata:
      labels:
        app: uber-frontend
    spec:
      containers:
      - name: uber-frontend
        image: leoncorreiasjsu/uber_frontend:latest
        ports:
        - containerPort: 3000

---

apiVersion: v1
kind: Service
metadata:
  name: uber-frontend-service
spec:
  type: LoadBalancer
  selector:
    app: uber-frontend
  ports:
  - protocol: TCP
    port: 3001
    targetPort: 3000