apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment
spec:
  selector:
    matchLabels:
      app: mysql
  replicas: 1
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: mysql:8.0 # Specify the MySQL version
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: leoncorreia
        - name: MYSQL_DATABASE
          value: uber_db
        - name: MYSQL_USER
          value: user
        - name: MYSQL_PASSWORD
          value: leoncorreia
        volumeMounts:
        - name: mysql-storage
          mountPath: /var/lib/mysql # MySQL data directory
      volumes:
      - name: mysql-storage
        persistentVolumeClaim:
          claimName: mysql-pvc

---

apiVersion: v1
kind: Service
metadata:
  name: mysql-service
spec:
  selector:
    app: mysql
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
  clusterIP: None # Use a headless service for cluster-aware MySQL setups
