# Generated by Django 5.1.3 on 2024-11-30 18:39

import django.db.models.deletion
import utils.validators.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="BillingInformation",
            fields=[
                (
                    "billing_id",
                    models.CharField(
                        max_length=11,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        validators=[
                            utils.validators.validators.DataValidators.validate_ssn
                        ],
                    ),
                ),
                ("date", models.DateField()),
                ("pickup_time", models.DateTimeField()),
                ("drop_off_time", models.DateTimeField()),
                (
                    "distance_covered",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("total_amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("source_location", models.CharField(max_length=255)),
                ("destination_location", models.CharField(max_length=255)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="users.customer"
                    ),
                ),
            ],
            options={
                "ordering": ["-date"],
            },
        ),
    ]
