# Generated by Django 4.1.13 on 2024-12-09 00:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("users", "0001_initial"),
        ("billing", "0001_initial"),
        ("driver", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="billinginformation",
            name="customer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="users.customer"
            ),
        ),
        migrations.AddField(
            model_name="billinginformation",
            name="driver",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="driver.driver"
            ),
        ),
        migrations.AddField(
            model_name="billinginformation",
            name="ride",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="users.booking",
            ),
        ),
    ]
