<<<<<<< HEAD
# Generated by Django 4.1.13 on 2024-12-08 05:18
=======
# Generated by Django 4.1.13 on 2024-12-08 03:26
>>>>>>> feature/leon

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("driver", "0001_initial"),
        ("users", "0001_initial"),
        ("billing", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="billinginformation",
            name="customer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="users.customer"
            ),
        ),
        migrations.AddField(
            model_name="billinginformation",
            name="driver",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="driver.driver"
            ),
        ),
    ]
