# Generated by Django 4.1.13 on 2024-12-08 05:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
        ("billing", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="billinginformation",
            name="ride",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="users.booking",
            ),
        ),
    ]
